name: polymer_category_links
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A model with 1 concept that uses dartlero.
homepage: http://ondart.me/
dependencies:
  dartlero:
    git: git://github.com/dzenanr/dartlero.git
  polymer: '>=0.15.4 <0.16.0'
transformers:
- polymer:
    entry_points: web/polymer_category_links.html