name: polymer_category_links
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A model with 1 concept that uses dartlero.
homepage: http://ondart.me/
dependencies:
  dartlero: any
  polymer: any
transformers:
- polymer:
    entry_points: web/polymer_category_links.html
